### ISSUE TITLE
Weblogic  12.2.1.3.0 and GraphQL Java Servlet - 7.3.3

### ISSUE THREAD

**Issue by radhikasenthilkumar** [graphql-java-kickstart/graphql-java-servlet#189] opened 2019-05-31 08:49 UTC
Hello I'm trying to deploy a GraphQL War  onto Weblogic 12.2.1.3 with graphql-java-servelt-7.3.3 jar.Whenever I load the url  with a content type of application/json am getting the following errors. 

Error 1:
[[ACTIVE] ExecuteThread: '74' for queue: 'weblogic.kernel.Default (self-tuning)'] INFO graphql.servlet.AbstractGraphQLHttpServlet - Bad POST request: parsing failed
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'ionType': was expecting ('true', 'false' or 'null')
 at [Source: (weblogic.servlet.internal.ServletInputStreamImpl); line: 1, column: 9]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:679)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3524)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2619)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:824)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:721)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:355)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1596)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1188)
	at graphql.servlet.GraphQLObjectMapper.readGraphQLRequest(GraphQLObjectMapper.java:65)
	at graphql.servlet.AbstractGraphQLHttpServlet.lambda$init$4(AbstractGraphQLHttpServlet.java:212)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:309)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:300)
	at graphql.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

Error 2:

[[ACTIVE] ExecuteThread: '62' for queue: 'weblogic.kernel.Default (self-tuning)'] INFO graphql.servlet.AbstractGraphQLHttpServlet - Bad POST request: parsing failed
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('.' (code 46)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (weblogic.servlet.internal.ServletInputStreamImpl); line: 1, column: 10]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:669)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:567)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2622)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:824)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:721)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:355)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1596)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1188)
	at graphql.servlet.GraphQLObjectMapper.readGraphQLRequest(GraphQLObjectMapper.java:65)
	at graphql.servlet.AbstractGraphQLHttpServlet.lambda$init$4(AbstractGraphQLHttpServlet.java:212)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:309)
	at graphql.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:300)
	at graphql.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

Getting these errors only when the war application is deployed on weblogic whereas it is working fine with Apache Tomcat Server.

**Comment by radhikasenthilkumar** [comment] 2019-06-10 12:50
Hi, 

In AbstractGraphQLHttpServlet class, there is a method query(queryInvoker, graphQLObjectMapper, invocationInputFactory.create(graphQLObjectMapper.readGraphQLRequest(inputStream), request, response), response);

**Comment by oliemansm** [comment] 2019-06-20 09:59
Are you using default enum value by any chance in your schema and using graphql-java-tools? Because the first problem seems to be reporting something similar I encountered in that case. This was caused by an incorrect serialization in graphql-java-tools, which has been fixed in 5.6.1.

It could also be that you're facing the same problem as reported in #170.

**Comment by oliemansm** [comment] 2019-11-14 17:40
Closing due to inactivity.

**Closed by oliemansm** 2019-11-14 17:40 UTC
Labels: bug
