### ISSUE TITLE
GraphQLServletListener.RequestCallback.onError not being called even though an exception throws

### ISSUE THREAD

**Issue by muhdalavu** [graphql-java-kickstart/graphql-java-servlet#451] opened 2022-06-23 13:59 UTC
**Describe the bug**
I should be able to handle the Exception from the GraphQLServletListener

**To Reproduce**
In Asynchronus Excecution, Even there are exception in the response, the onError callback not being called.

**Expected behavior**
OnError mothod should be called 
[In the below code the exceptionlly method not being called.]
[file](https://github.com/graphql-java-kickstart/graphql-java-servlet/blob/0b010c5c0804183a8a5971a7e55a746fb681924b/graphql-java-servlet/src/main/java/graphql/kickstart/servlet/HttpRequestInvokerImpl.java#L115)

```
private CompletableFuture<Void> handle(
      FutureExecutionResult futureResult,
      HttpServletRequest request,
      HttpServletResponse response,
      ListenerHandler listenerHandler) {
    return futureResult
        .thenApplyQueryResult()
        .thenAccept(
            it -> {
              listenerHandler.beforeFlush();
              writeResultResponse(futureResult.getInvocationInput(), it, request, response);
            })
        .thenAccept(it -> listenerHandler.onSuccess())
        .exceptionally(
            t ->
                writeErrorResponse(
                    futureResult.getInvocationInput(), request, response, listenerHandler, t))
        .thenAccept(it -> listenerHandler.onFinally());
  }

```

<img width="1400" alt="Screenshot 2022-06-23 at 7 24 41 PM" src="https://user-images.githubusercontent.com/6194769/175316444-c12e7953-b9f7-4197-88f6-9f08e9fa59ec.png">

**Comment by oliemansm** [comment] 2022-08-17 17:45
Do you have an example project or even better a unit test in a fork of this project reproducing this issue?

**Comment by federicorispo** [comment] 2023-06-16 15:09
I think we can close this bug since the code is changed and now the `handle` method calls the listenerHandler.onError when an exception is catched.

See: https://github.com/graphql-java-kickstart/graphql-java-servlet/pull/442/files#diff-a166ddb02fc54c24bbd3a3759107eebb065981ac3824adf877c1e134afd1a3ccR107-R118

**Closed** 2023-12-19 07:37 UTC
Labels: bug
