### ISSUE TITLE
null pointer  (and deprecation) upon upgrade from 6.2.0 to 7.1.1

### ISSUE THREAD

**Issue by MarkNenadov** [graphql-java-kickstart/graphql-java-servlet#139] opened 2018-12-10 21:23 UTC
I upgrade from the kickstart graphql-java-servlet 6.2.0 to 7.1.1.

I have the following code:

`            SimpleGraphQLHttpServlet servlet = SimpleGraphQLHttpServlet.newBuilder( graphQLInvocationInputFactory )
                    .withObjectMapper( GraphQLObjectMapper.newBuilder().withGraphQLErrorHandler( errorHandler ).build() ).build();
`

The last build (the withObjectMapper().build()) appears to be returning null, so in my next line I get a null pointer.

`            servlet.addListener( new GraphQLServletListener() {
`

Upon a closer look, I have noticed that SimpleGraphQLHttpServlet.Builder.build() is deprecated.

Am I missing something here? Is there another way I should be doing this?

**Comment by oliemansm** [comment] 2019-01-02 15:46
As you can see in the code of the builder it always returns a new instance and never `null`. So the NPE is actually caused by something else. Is the `errorHandler` you're passing in there `null` maybe?

```java
public SimpleGraphQLHttpServlet build() {
            GraphQLConfiguration configuration = GraphQLConfiguration.with(invocationInputFactory)
                    .with(queryInvoker)
                    .with(graphQLObjectMapper)
                    .with(listeners != null ? listeners : new ArrayList<>())
                    .with(asyncServletMode)
                    .build();
            return new SimpleGraphQLHttpServlet(configuration);
        }
```

**Comment by MarkNenadov** [comment] 2019-01-02 20:51
@oliemansm Thanks. The errorHandler was not null. 

I now see that the NPE was happening inside AbstractGraphQLHttpServlet.addListener() and "this.configuration" is what is null.

Here is more context (in this snippet schema, contextBuilder, and errorHandler are all not null):

`            GraphQLInvocationInputFactory graphQLInvocationInputFactory = GraphQLInvocationInputFactory.newBuilder( schema ).withGraphQLContextBuilder( contextBuilder ).build();

            SimpleGraphQLHttpServlet servlet = SimpleGraphQLHttpServlet.newBuilder( graphQLInvocationInputFactory )
                    .withObjectMapper( GraphQLObjectMapper.newBuilder().withGraphQLErrorHandler( errorHandler ).build() ).build();

            servlet.addListener( new GraphQLServletListener() {
                @Override
                public GraphQLServletListener.RequestCallback onRequest( HttpServletRequest request, HttpServletResponse response ) {
                    return new GraphQLServletListener.RequestCallback() {
                        @Override
                        public void onSuccess( HttpServletRequest request, HttpServletResponse response ) {

                        }

                        @Override
                        public void onError( HttpServletRequest request, HttpServletResponse response, Throwable throwable ) {

                        }

                        @Override
                        public void onFinally( HttpServletRequest request, HttpServletResponse response ) {

                        }
                    };
                };
            });
`

**Comment by MarkNenadov** [comment] 2019-01-02 20:55
So as far as I can tell, between my call to build() and my call to addListener(), the servlet's configuration is being set back to null?

**Comment by oliemansm** [comment] 2019-02-16 10:58
Don't see how that could be happening. You sure it's not the `add` method within `GraphQLConfiguration` that's causing the NPE because `listeners` could be `null` at this point?
```java
listeners.add(listener);
```

Have you tried moving to the `GraphQLHttpServlet` class instead of using `SimpleGraphQLHttpServlet`, since that ensures `listeners` is never `null`?

```java
GraphQLConfiguration config = GraphQLConfiguration.with(graphQLInvocationInputFactory)
    .with(GraphQLObjectMapper.newBuilder().withGraphQLErrorHandler( errorHandler ).build())
    .build();
config.add(new GraphQLServletListener() {
            @Override
            public GraphQLServletListener.RequestCallback onRequest( HttpServletRequest request, HttpServletResponse response ) {
                return new GraphQLServletListener.RequestCallback() {
                    @Override
                    public void onSuccess( HttpServletRequest request, HttpServletResponse response ) {

                    }

                    @Override
                    public void onError( HttpServletRequest request, HttpServletResponse response, Throwable throwable ) {

                    }

                    @Override
                    public void onFinally( HttpServletRequest request, HttpServletResponse response ) {

                    }
                };
            };
        });
GraphQLHttpServlet servlet = GraphQLHttpServlet.with(config);
```

**Comment by oliemansm** [comment] 2019-03-23 07:47
Closing due to inactivity. If you still need help with this, feel free to reopen the issue with a follow-up question.

**Closed by oliemansm** 2019-03-23 07:47 UTC
Labels: question
